# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installing Node
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.18.3
      - name: GitHub Action for NPM/Chrome
        uses: daleobrien/npm-with-chrome-browser-action@v1.0.1
        with:
          cmd: npm install
      - name: creating build
        run: npm run build
        # Runs a set of commands using the runners shell
      - name: Installing surge
        run: npm install --global surge
      
      - name: deploying surge
        run: surge ./client/build http://expensetrackersimple.surge.sh/ --token ${{secrets.Surge_Token}}
